#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Agrega 4 celdas nuevas al final del notebook 05A_datos_terreno.ipynb:
  1. Markdown: Sección 17 - Series temporales tendencia central
  2. Code: Series temporales con misma escala X-Y, solo tendencia central
  3. Markdown: Sección 18 - Boxplot horizontal sin outliers
  4. Code: Boxplot horizontal + actualización mapa interactivo

También modifica la celda 47 (panel SIG) para que el boxplot del popup
sea horizontal y sin outliers.
"""
import json
import uuid
from pathlib import Path

NB_PATH = Path(__file__).resolve().parent.parent / "notebooks" / "05A_datos_terreno.ipynb"

def make_cell(cell_type, source_lines, language="python"):
    cell = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source_lines,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
        cell["metadata"]["language_info"] = {"name": language}
    return cell

# ── Celda markdown: Sección 17 ──────────────────────────────────────────
md_series = make_cell("markdown", [
    "---\n",
    "## 17. Series Temporales — Tendencia Central (misma escala X-Y)\n",
    "\n",
    "Visualización sin picos: se filtran los valores extremos (fuera del rango IQR ± 1.5×IQR) y se aplica una mediana móvil (ventana = 3 puntos) para mostrar únicamente la **tendencia central** del flujo.  \n",
    "Todas las estaciones comparten la **misma escala X e Y**, facilitando la comparación directa y la alineación con el rango de referencia MATLAB (banda gris)."
])

# ── Celda código: Series temporales tendencia central ────────────────────
code_series = make_cell("code", [
    "# =============================================================================\n",
    "# CELDA 25: SERIES TEMPORALES — TENDENCIA CENTRAL (MISMA ESCALA X-Y)\n",
    "# =============================================================================\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.dates as mdates\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "plt.rcParams.update({\n",
    '    "font.family": "serif",\n',
    '    "font.serif": ["Times New Roman", "DejaVu Serif"],\n',
    '    "font.size": 11,\n',
    '    "axes.labelsize": 12,\n',
    '    "axes.titlesize": 13,\n',
    '    "figure.dpi": 150,\n',
    '    "savefig.dpi": 300,\n',
    "})\n",
    "\n",
    "_tc_hex = {\n",
    "    'TC1': '#1f77b4', 'TC2': '#ff7f0e', 'TC3': '#2ca02c',\n",
    "    'TC4': '#9467bd', 'TC5': '#d62728'\n",
    "}\n",
    "_pair_dash = {'sup_int': '-', 'int_inf': '--', 'sup_inf': '-.'}\n",
    "_pair_lbl_tc = {\n",
    "    'sup_int': 'Sup → Int ($z_1$–$z_2$)',\n",
    "    'int_inf': 'Int → Inf ($z_2$–$z_3$)',\n",
    "    'sup_inf': 'Sup → Inf ($z_1$–$z_3$)'\n",
    "}\n",
    "\n",
    "# ── 1) Filtrar outliers por IQR y suavizar con mediana móvil ─────────────\n",
    "filtered_series = {}\n",
    "all_filtered_vals = []\n",
    "all_dates = []\n",
    "\n",
    "for pair_name, df_flux in flux_ts_results.items():\n",
    "    df_valid = df_flux[df_flux['quality_flag'] == 0].copy()\n",
    "    if len(df_valid) == 0 or 'flux_hatch_amplitude_mm_day' not in df_valid.columns:\n",
    "        continue\n",
    "    vals = df_valid['flux_hatch_amplitude_mm_day'].dropna()\n",
    "    q1, q3 = vals.quantile(0.25), vals.quantile(0.75)\n",
    "    iqr_v = q3 - q1\n",
    "    lower, upper = q1 - 1.5 * iqr_v, q3 + 1.5 * iqr_v\n",
    "\n",
    "    mask_iqr = (df_valid['flux_hatch_amplitude_mm_day'] >= lower) & \\\n",
    "               (df_valid['flux_hatch_amplitude_mm_day'] <= upper)\n",
    "    df_filt = df_valid.loc[mask_iqr].copy()\n",
    "    df_filt['flux_smooth'] = (\n",
    "        df_filt['flux_hatch_amplitude_mm_day']\n",
    "        .rolling(window=3, center=True, min_periods=1)\n",
    "        .median()\n",
    "    )\n",
    "    filtered_series[pair_name] = df_filt\n",
    "    all_filtered_vals.extend(df_filt['flux_smooth'].dropna().tolist())\n",
    "    all_dates.extend(df_filt['datetime'].tolist())\n",
    "\n",
    "# ── 2) Límites globales X-Y ─────────────────────────────────────────────\n",
    "y_lo = np.percentile(all_filtered_vals, 1)\n",
    "y_hi = np.percentile(all_filtered_vals, 99)\n",
    "y_pad = (y_hi - y_lo) * 0.08\n",
    "y_lim = (y_lo - y_pad, y_hi + y_pad)\n",
    "x_lim = (min(all_dates), max(all_dates))\n",
    "\n",
    "# ── 3) Gráfico con misma escala ─────────────────────────────────────────\n",
    "n_tcs = len(ACTIVE_TCS)\n",
    "fig, axes = plt.subplots(n_tcs, 1, figsize=(14, 3.0 * n_tcs),\n",
    "                          sharex=True, sharey=True)\n",
    "if n_tcs == 1:\n",
    "    axes = [axes]\n",
    "\n",
    "for ax_idx, (ax, tc_name) in enumerate(zip(axes, ACTIVE_TCS)):\n",
    "    color = _tc_hex[tc_name]\n",
    "    ref = MATLAB_REFERENCE.get(tc_name, {})\n",
    "    tp = THERMAL_PARAMS_LAB[tc_name]\n",
    "\n",
    "    for pair_name, df_filt in filtered_series.items():\n",
    "        if tc_name not in pair_name:\n",
    "            continue\n",
    "        pt = pair_name.split('_', 1)[1]\n",
    "        ax.plot(\n",
    "            df_filt['datetime'], df_filt['flux_smooth'],\n",
    "            linestyle=_pair_dash.get(pt, '-'),\n",
    "            color=color, alpha=0.85, linewidth=1.4,\n",
    "            label=_pair_lbl_tc.get(pt, pt)\n",
    "        )\n",
    "\n",
    "    if ref:\n",
    "        ax.axhspan(ref['min'], ref['max'], alpha=0.12, color='#888888',\n",
    "                    zorder=0, label=f'Rango MATLAB ({ref[\"min\"]}–{ref[\"max\"]})')\n",
    "        ax.axhline(y=ref['mean'], color='#666666', linestyle='--',\n",
    "                    linewidth=1.0, alpha=0.7, zorder=1,\n",
    "                    label=f'MATLAB prom: {ref[\"mean\"]} mm/d')\n",
    "\n",
    "    ax.axhline(y=0, color='k', linestyle='-', linewidth=0.5, alpha=0.3)\n",
    "    ax.grid(True, axis='both', alpha=0.35, linewidth=0.4, color='#aaaaaa')\n",
    "    ax.spines['top'].set_visible(False)\n",
    "    ax.spines['right'].set_visible(False)\n",
    "    ax.set_ylabel('$q$ (mm/día)', fontsize=11)\n",
    "    title_str = f'{tc_name} — {tp[\"USCS\"]}'\n",
    "    if ref:\n",
    "        title_str += f' | ref MATLAB: {ref[\"mean\"]} mm/d'\n",
    "    ax.set_title(title_str, fontsize=10, fontweight='bold', pad=6, loc='left')\n",
    "    ax.legend(loc='upper right', fontsize=7.5, frameon=True,\n",
    "              framealpha=0.92, edgecolor='#ccc', ncol=2, handlelength=2.5)\n",
    "    ax.xaxis.set_major_formatter(mdates.DateFormatter('%d-%b'))\n",
    "    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))\n",
    "    ax.tick_params(axis='both', labelsize=9)\n",
    "\n",
    "axes[0].set_ylim(y_lim)\n",
    "axes[0].set_xlim(x_lim)\n",
    "axes[-1].set_xlabel('Fecha', fontsize=11)\n",
    "\n",
    "fig.suptitle(\n",
    "    'Series Temporales de Flujo — Tendencia Central (sin picos)\\n'\n",
    "    'Misma escala X-Y — Río Cuncumén — Dic 2025 – Feb 2026',\n",
    "    fontsize=13, fontweight='bold', y=1.01\n",
    ")\n",
    "fig.tight_layout()\n",
    "\n",
    "for ext in ('png', 'pdf'):\n",
    "    fig.savefig(img_dir / f'series_tendencia_central_informe.{ext}',\n",
    "                dpi=300, bbox_inches='tight', facecolor='white', pad_inches=0.2)\n",
    "print(f'✅ Series tendencia central guardadas en {img_dir}')\n",
    "print(f'   → series_tendencia_central_informe.png | .pdf')\n",
    "plt.show()"
])

# ── Celda markdown: Sección 18 ──────────────────────────────────────────
md_boxplot = make_cell("markdown", [
    "---\n",
    "## 18. Boxplot Horizontal — Tendencia Central (sin outliers)\n",
    "\n",
    "Boxplot con orientación **horizontal** mostrando únicamente el rango intercuartil y los bigotes (sin outliers).  \n",
    "La escala se ajusta automáticamente al rango de los bigotes para maximizar la resolución visual de las tendencias centrales.  \n",
    "Se regenera también el **mapa interactivo** con el boxplot horizontal actualizado en cada popup."
])

# ── Celda código: Boxplot horizontal + regenerar mapa ────────────────────
code_boxplot = make_cell("code", [
    "# =============================================================================\n",
    "# CELDA 26: BOXPLOT HORIZONTAL — TENDENCIA CENTRAL (SIN OUTLIERS)\n",
    "#           + REGENERACIÓN DEL MAPA INTERACTIVO CON BOXPLOT ACTUALIZADO\n",
    "# =============================================================================\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import numpy as np\n",
    "\n",
    "# ── Recopilar flujos Hatch-Amplitude de las series temporales ──────────\n",
    "boxplot_data_h = {}\n",
    "for pair_name, df_flux in flux_ts_results.items():\n",
    "    tc = pair_name.split('_')[0]\n",
    "    df_ok = df_flux[df_flux['quality_flag'] == 0]\n",
    "    if 'flux_hatch_amplitude_mm_day' in df_ok.columns:\n",
    "        vals = df_ok['flux_hatch_amplitude_mm_day'].dropna().values\n",
    "        if tc not in boxplot_data_h:\n",
    "            boxplot_data_h[tc] = []\n",
    "        boxplot_data_h[tc].extend(vals.tolist())\n",
    "\n",
    "plt.rcParams.update({\n",
    '    "font.family": "serif",\n',
    '    "font.serif": ["Times New Roman", "DejaVu Serif"],\n',
    '    "font.size": 11,\n',
    '    "axes.labelsize": 12,\n',
    '    "axes.titlesize": 13,\n',
    '    "figure.dpi": 150,\n',
    '    "savefig.dpi": 300,\n',
    "})\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 5))\n",
    "\n",
    "tc_order = ['TC1', 'TC2', 'TC3', 'TC4', 'TC5']\n",
    "data_list_h = [np.array(boxplot_data_h.get(tc, [])) for tc in tc_order]\n",
    "positions = np.arange(1, len(tc_order) + 1)\n",
    "colors_box = [TC_COLORS[tc] for tc in tc_order]\n",
    "\n",
    "# ── Boxplot HORIZONTAL, sin outliers ──────────────────────────────────\n",
    "bp = ax.boxplot(\n",
    "    data_list_h, positions=positions, patch_artist=True, widths=0.55,\n",
    "    vert=False, showfliers=False,\n",
    "    medianprops=dict(color='black', linewidth=2.0),\n",
    "    whiskerprops=dict(linewidth=1.2),\n",
    "    capprops=dict(linewidth=1.2),\n",
    ")\n",
    "for patch, color in zip(bp['boxes'], colors_box):\n",
    "    patch.set_facecolor(color)\n",
    "    patch.set_alpha(0.55)\n",
    "    patch.set_edgecolor('black')\n",
    "    patch.set_linewidth(1.0)\n",
    "\n",
    "# ── Referencia MATLAB (diamantes) ─────────────────────────────────────\n",
    "for i, tc in enumerate(tc_order):\n",
    "    ref = MATLAB_REFERENCE.get(tc, {})\n",
    "    if ref:\n",
    "        ax.scatter(ref['mean'], positions[i], marker='D', s=90, facecolors='none',\n",
    "                   edgecolors='#1565C0', linewidths=1.5, zorder=6,\n",
    "                   label='Ref. MATLAB VFLUX2' if i == 0 else None)\n",
    "\n",
    "# ── Anotaciones: mediana, n ───────────────────────────────────────────\n",
    "for i, (tc, vals) in enumerate(zip(tc_order, data_list_h)):\n",
    "    if len(vals) == 0:\n",
    "        continue\n",
    "    med = np.median(vals)\n",
    "    ax.text(med, positions[i] + 0.35, f'med={med:.0f} | n={len(vals)}',\n",
    "            ha='center', va='bottom', fontsize=8, color='#333',\n",
    "            bbox=dict(boxstyle='round,pad=0.2', facecolor='white',\n",
    "                      alpha=0.8, edgecolor='none'))\n",
    "\n",
    "# ── Etiquetas con clasificación USCS ──────────────────────────────────\n",
    "uscs_labels = [f\"{tc} ({THERMAL_PARAMS_LAB[tc]['USCS']})\" for tc in tc_order]\n",
    "ax.set_yticks(positions)\n",
    "ax.set_yticklabels(uscs_labels, fontsize=10, fontweight='bold')\n",
    "\n",
    "# ── Ajustar escala X a rango de bigotes ───────────────────────────────\n",
    "whisker_vals = [w.get_xdata() for w in bp['whiskers']]\n",
    "all_whiskers = np.concatenate(whisker_vals)\n",
    "w_min, w_max = all_whiskers.min(), all_whiskers.max()\n",
    "x_margin = (w_max - w_min) * 0.12\n",
    "ax.set_xlim(w_min - x_margin, w_max + x_margin)\n",
    "\n",
    "ax.set_xlabel('Flujo vertical $q$ (mm/día)', fontsize=12)\n",
    "ax.set_title(\n",
    "    'Distribución del Flujo Hatch-Amplitude — Tendencia Central\\n'\n",
    "    'Río Cuncumén — Dic 2025 a Feb 2026 — horizontal, sin outliers',\n",
    "    fontsize=13, fontweight='bold', pad=12\n",
    ")\n",
    "ax.axvline(x=0, color='k', linestyle='-', linewidth=0.6, alpha=0.4)\n",
    "ax.grid(True, axis='x', alpha=0.4, linewidth=0.5, color='#999999')\n",
    "ax.spines['top'].set_visible(False)\n",
    "ax.spines['right'].set_visible(False)\n",
    "\n",
    "legend_items = [\n",
    "    mpatches.Patch(facecolor='#aaa', alpha=0.55, edgecolor='k', linewidth=0.8,\n",
    "                   label='Rango IQR (Q1–Q3)'),\n",
    "    plt.Line2D([0], [0], color='k', linewidth=2.0, label='Mediana'),\n",
    "    plt.Line2D([0], [0], marker='D', color='w', markerfacecolor='none',\n",
    "               markeredgecolor='#1565C0', markersize=8, markeredgewidth=1.5,\n",
    "               label='Ref. MATLAB VFLUX2'),\n",
    "]\n",
    "ax.legend(handles=legend_items, loc='lower right', frameon=True,\n",
    "          framealpha=0.92, edgecolor='#ccc', fontsize=9)\n",
    "\n",
    "fig.tight_layout()\n",
    "for ext in ('png', 'pdf'):\n",
    "    fig.savefig(img_dir / f'boxplot_horizontal_tendencia_central.{ext}',\n",
    "                dpi=300, bbox_inches='tight', facecolor='white', pad_inches=0.25)\n",
    "print(f'✅ Boxplot horizontal guardado en {img_dir}')\n",
    "print(f'   → boxplot_horizontal_tendencia_central.png | .pdf')\n",
    "plt.show()\n",
    "\n",
    "# ── Tabla resumen ─────────────────────────────────────────────────────\n",
    "print(f\"\\n{'='*90}\")\n",
    "print(f\" RESUMEN ESTADÍSTICO — TENDENCIA CENTRAL (sin outliers) \".center(90))\n",
    "print(f\"{'='*90}\")\n",
    "print(f\"{'TC':<8} {'n':>5} {'Media':>10} {'Mediana':>10} {'Q1':>10} \"\n",
    "      f\"{'Q3':>10} {'Whisker↓':>10} {'Whisker↑':>10} {'MATLAB':>10}\")\n",
    "print(f\"{'─'*90}\")\n",
    "for i, (tc, vals) in enumerate(zip(tc_order, data_list_h)):\n",
    "    if len(vals) == 0:\n",
    "        continue\n",
    "    ref_m = MATLAB_REFERENCE.get(tc, {}).get('mean', np.nan)\n",
    "    q1, q3 = np.percentile(vals, 25), np.percentile(vals, 75)\n",
    "    iqr_v = q3 - q1\n",
    "    wl = max(vals.min(), q1 - 1.5 * iqr_v)\n",
    "    wu = min(vals.max(), q3 + 1.5 * iqr_v)\n",
    "    print(f\"{tc:<8} {len(vals):>5} {np.mean(vals):>10.1f} {np.median(vals):>10.1f} \"\n",
    "          f\"{q1:>10.1f} {q3:>10.1f} {wl:>10.1f} {wu:>10.1f} {ref_m:>10}\")\n",
    "print(f\"\\n  Unidad: mm/día  |  Método: Hatch et al. (2006)  |  Ventana: 48 h, paso 12 h\")\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "# REGENERAR MAPA SIG INTEGRADO con boxplot horizontal sin outliers\n",
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "import json as _json\n",
    "import plotly.graph_objects as go\n",
    "import folium, folium.plugins\n",
    "from pyproj import Transformer\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "_tf2 = Transformer.from_crs('EPSG:32719', 'EPSG:4326', always_xy=True)\n",
    "coords_wgs84_v2 = {}\n",
    "for _st, _utm in STATION_COORDS_UTM.items():\n",
    "    _lon, _lat = _tf2.transform(_utm['easting'], _utm['northing'])\n",
    "    coords_wgs84_v2[_st] = {'lat': _lat, 'lon': _lon}\n",
    "\n",
    "_pos_short2 = {'surface': 'sup', 'intermediate': 'int', 'deep': 'inf'}\n",
    "_pos_dash2 = {'surface': 'solid', 'intermediate': 'dash', 'deep': 'dot'}\n",
    "_tc_hex_p2 = {'TC1':'#1f77b4','TC2':'#ff7f0e','TC3':'#e377c2',\n",
    "              'TC4':'#2ca02c','TC5':'#d62728'}\n",
    "_pair_col2 = {'sup_int':'#0072BD','int_inf':'#D95319','sup_inf':'#EDB120'}\n",
    "_pair_lbl2 = {'sup_int':'sup→int','int_inf':'int→inf','sup_inf':'sup→inf'}\n",
    "_SMAP2 = {\n",
    "    'TC1': {'surface':0.00,'intermediate':0.28,'deep':0.56},\n",
    "    'TC2': {'surface':0.00,'intermediate':0.20,'deep':0.40},\n",
    "    'TC3': {'surface':0.00,'intermediate':0.20,'deep':0.40},\n",
    "    'TC4': {'surface':0.00,'intermediate':0.28,'deep':0.56},\n",
    "    'TC5': {'surface':0.00,'intermediate':0.28,'deep':0.56},\n",
    "}\n",
    "\n",
    "_mask2 = (df_aligned['fecha'] >= cutoff_start) & (df_aligned['fecha'] <= cutoff_end)\n",
    "_df_pop2 = df_aligned[_mask2].copy()\n",
    "\n",
    "_JS_TMPL2 = '''<script>\n",
    "(function(){\n",
    "  var FR=__DATA__;\n",
    "  var pk=Object.keys(FR);\n",
    "  function pct(a,p){var s=a.slice().sort(function(x,y){return x-y});\n",
    "    var i=p/100*(s.length-1),lo=Math.floor(i),hi=Math.ceil(i);\n",
    "    return lo===hi?s[lo]:s[lo]+(i-lo)*(s[hi]-s[lo]);}\n",
    "  function upd(xMin,xMax){\n",
    "    var tb=document.getElementById(\"stats-body\");if(!tb)return;\n",
    "    tb.innerHTML=\"\";\n",
    "    var ri=document.getElementById(\"rng-info\");\n",
    "    if(ri){ri.textContent=xMin&&xMax\n",
    "      ?\"Ventana: \"+new Date(xMin).toLocaleDateString(\"es-CL\")+\" \\u2013 \"+new Date(xMax).toLocaleDateString(\"es-CL\")\n",
    "      :\"Ventana: serie completa\";}\n",
    "    var all=[];\n",
    "    pk.forEach(function(k){\n",
    "      var dt=FR[k].dt,v=FR[k].flux,f=[];\n",
    "      for(var i=0;i<dt.length;i++){if((!xMin||dt[i]>=xMin)&&(!xMax||dt[i]<=xMax))f.push(v[i]);}\n",
    "      if(!f.length)return; all=all.concat(f);\n",
    "      var q1=pct(f,25),md=pct(f,50),q3=pct(f,75);\n",
    "      var mn=f.reduce(function(a,b){return a+b},0)/f.length;\n",
    "      tb.innerHTML+=\"<tr><td style='color:\"+FR[k].color+\"'>\"+FR[k].label+\"</td>\"\n",
    "        +\"<td>\"+q1.toFixed(0)+\"</td><td style='font-weight:600'>\"+md.toFixed(0)+\"</td>\"\n",
    "        +\"<td>\"+q3.toFixed(0)+\"</td><td>\"+mn.toFixed(0)+(mn>0?\" \\u2193\":\" \\u2191\")\n",
    "        +\"</td><td>\"+f.length+\"</td></tr>\";\n",
    "    });\n",
    "    if(all.length){\n",
    "      var tq1=pct(all,25),tmd=pct(all,50),tq3=pct(all,75);\n",
    "      var tmn=all.reduce(function(a,b){return a+b},0)/all.length;\n",
    "      tb.innerHTML+=\"<tr style='border-top:2px solid #333;font-weight:700'><td>TOTAL</td>\"\n",
    "        +\"<td>\"+tq1.toFixed(0)+\"</td><td>\"+tmd.toFixed(0)+\"</td>\"\n",
    "        +\"<td>\"+tq3.toFixed(0)+\"</td><td>\"+tmn.toFixed(0)+\"</td>\"\n",
    "        +\"<td>\"+all.length+\"</td></tr>\";}\n",
    "  }\n",
    "  upd(null,null);\n",
    "  var fc=document.getElementById(\"flux-chart\");\n",
    "  if(fc)fc.on(\"plotly_relayout\",function(ev){\n",
    "    var xMin=ev[\"xaxis.range[0]\"]||(ev[\"xaxis.range\"]&&ev[\"xaxis.range\"][0])||null;\n",
    "    var xMax=ev[\"xaxis.range[1]\"]||(ev[\"xaxis.range\"]&&ev[\"xaxis.range\"][1])||null;\n",
    "    if(ev[\"xaxis.autorange\"]){xMin=null;xMax=null;}\n",
    "    upd(xMin,xMax);\n",
    "  });\n",
    "})();</script>'''\n",
    "\n",
    "\n",
    "def _build_popup_v2(tc):\n",
    "    \"\"\"Popup HTML con boxplot horizontal y sin outliers.\"\"\"\n",
    "    utm_c = STATION_COORDS_UTM[tc]\n",
    "    color = _tc_hex_p2.get(tc, '#555')\n",
    "    tp = THERMAL_PARAMS_LAB[tc]\n",
    "    tc_map = TC_CONFIG[tc]\n",
    "    ds = sorted(set(_SMAP2[tc].values()))\n",
    "    ds_str = ' / '.join(f'{d*100:.0f}' for d in ds) + ' cm'\n",
    "\n",
    "    # ── 1) Serie de temperatura ──────────────────────────────────────\n",
    "    fig_t = go.Figure()\n",
    "    for pos in ['surface', 'intermediate', 'deep']:\n",
    "        col = tc_map[pos]\n",
    "        dcm = depths_m[col] * 100\n",
    "        d = _df_pop2.dropna(subset=[col])\n",
    "        st = max(1, len(d) // 200)\n",
    "        fig_t.add_trace(go.Scatter(\n",
    "            x=d.iloc[::st]['fecha'], y=d.iloc[::st][col], mode='lines',\n",
    "            name=f'{_pos_short2[pos]} ({dcm:.0f}cm)',\n",
    "            line=dict(width=1.5, dash=_pos_dash2[pos]),\n",
    "            hovertemplate='%{x|%d-%b %H:%M}<br>%{y:.1f}°C<extra></extra>'))\n",
    "    fig_t.update_layout(\n",
    "        title=dict(text='Temperatura', font=dict(size=12)),\n",
    "        xaxis=dict(showgrid=False, tickfont=dict(size=8), tickformat='%d-%b'),\n",
    "        yaxis=dict(title=dict(text='°C', font=dict(size=9)),\n",
    "                   tickfont=dict(size=8)),\n",
    "        template='plotly_white', height=170, width=480,\n",
    "        margin=dict(l=35, r=8, t=28, b=28),\n",
    "        legend=dict(orientation='h', font=dict(size=8),\n",
    "                    y=1.15, x=0.5, xanchor='center'))\n",
    "    ht = fig_t.to_html(include_plotlyjs=False, full_html=False,\n",
    "                        config={'displayModeBar': False})\n",
    "\n",
    "    # ── 2) Flujo Hatch-Amplitude con RANGE-SLIDER ───────────────────\n",
    "    fig_f = go.Figure()\n",
    "    raw = {}\n",
    "    has_f = False\n",
    "    for pn, dff in flux_ts_results.items():\n",
    "        if tc not in pn:\n",
    "            continue\n",
    "        dv = dff[dff['quality_flag'] == 0]\n",
    "        if len(dv) == 0 or 'flux_hatch_amplitude_mm_day' not in dv.columns:\n",
    "            continue\n",
    "        has_f = True\n",
    "        pt = pn.split('_', 1)[1]\n",
    "        raw[pt] = {\n",
    "            'dt': dv['datetime'].dt.strftime('%Y-%m-%dT%H:%M:%S').tolist(),\n",
    "            'flux': dv['flux_hatch_amplitude_mm_day'].round(2).tolist(),\n",
    "            'label': _pair_lbl2.get(pt, pt),\n",
    "            'color': _pair_col2.get(pt, '#888')}\n",
    "        sf = max(1, len(dv) // 150)\n",
    "        fig_f.add_trace(go.Scatter(\n",
    "            x=dv.iloc[::sf]['datetime'],\n",
    "            y=dv.iloc[::sf]['flux_hatch_amplitude_mm_day'],\n",
    "            mode='lines+markers', name=_pair_lbl2.get(pt, pt),\n",
    "            marker=dict(size=3),\n",
    "            line=dict(width=1.5, color=_pair_col2.get(pt, '#888')),\n",
    "            hovertemplate='%{x|%d-%b %H:%M}<br>%{y:.0f} mm/d<extra></extra>'))\n",
    "\n",
    "    ref = MATLAB_REFERENCE.get(tc, {})\n",
    "    if ref and has_f:\n",
    "        fig_f.add_hrect(y0=ref['min'], y1=ref['max'],\n",
    "                        fillcolor='gray', opacity=0.12, line_width=0)\n",
    "        fig_f.add_hline(y=ref['mean'], line_dash='dash', line_color='gray',\n",
    "                        line_width=1,\n",
    "                        annotation_text=f'MATLAB {ref[\"mean\"]}',\n",
    "                        annotation_position='top right',\n",
    "                        annotation_font_size=8)\n",
    "\n",
    "    fig_f.update_layout(\n",
    "        title=dict(text='Flujo Hatch-Amplitude (selector interactivo)',\n",
    "                   font=dict(size=11)),\n",
    "        xaxis=dict(\n",
    "            rangeslider=dict(visible=True, thickness=0.12),\n",
    "            rangeselector=dict(\n",
    "                buttons=[\n",
    "                    dict(count=3, label='3d', step='day', stepmode='backward'),\n",
    "                    dict(count=7, label='1sem', step='day', stepmode='backward'),\n",
    "                    dict(count=14, label='2sem', step='day', stepmode='backward'),\n",
    "                    dict(step='all', label='Todo')],\n",
    "                font=dict(size=8)),\n",
    "            showgrid=False, tickfont=dict(size=8), tickformat='%d-%b'),\n",
    "        yaxis=dict(title=dict(text='mm/d', font=dict(size=9)),\n",
    "                   tickfont=dict(size=8)),\n",
    "        template='plotly_white', height=230, width=480,\n",
    "        margin=dict(l=40, r=8, t=35, b=25),\n",
    "        legend=dict(orientation='h', font=dict(size=7),\n",
    "                    y=1.18, x=0.5, xanchor='center'))\n",
    "    hf = fig_f.to_html(include_plotlyjs=False, full_html=False,\n",
    "                        config={'displayModeBar': False}, div_id='flux-chart')\n",
    "\n",
    "    # ── 3) Boxplot HORIZONTAL, sin outliers ──────────────────────────\n",
    "    fig_b = go.Figure()\n",
    "    _bp_all = []\n",
    "    for pk_key in [p for p in all_flux_results.keys() if tc in p]:\n",
    "        ps = pk_key.split(': ')[1] if ': ' in pk_key else pk_key\n",
    "        ts_k = f\"{tc}_{ps.replace('-', '_')}\"\n",
    "        if ts_k in flux_ts_results:\n",
    "            dv2 = flux_ts_results[ts_k]\n",
    "            dv2 = dv2[dv2['quality_flag'] == 0]\n",
    "            if 'flux_hatch_amplitude_mm_day' in dv2.columns:\n",
    "                vb = dv2['flux_hatch_amplitude_mm_day'].dropna().values\n",
    "                if len(vb) > 0:\n",
    "                    _bp_all.extend(vb.tolist())\n",
    "                    fig_b.add_trace(go.Box(\n",
    "                        x=vb, name=ps, marker_color=color,\n",
    "                        boxmean=True, opacity=0.8,\n",
    "                        boxpoints=False,\n",
    "                        orientation='h',\n",
    "                        hovertemplate='%{x:.0f} mm/d<extra></extra>'))\n",
    "    # Ajustar rango X al rango de bigotes\n",
    "    _xrng = None\n",
    "    if _bp_all:\n",
    "        _bpa = np.array(_bp_all)\n",
    "        _q1b, _q3b = np.percentile(_bpa, 25), np.percentile(_bpa, 75)\n",
    "        _iqrb = _q3b - _q1b\n",
    "        _xrng = [max(_bpa.min(), _q1b - 1.5*_iqrb) - _iqrb*0.15,\n",
    "                 min(_bpa.max(), _q3b + 1.5*_iqrb) + _iqrb*0.15]\n",
    "    fig_b.update_layout(\n",
    "        title=dict(text='Boxplot Hatch-Amp (tendencia central)', font=dict(size=11)),\n",
    "        xaxis=dict(title=dict(text='mm/d', font=dict(size=9)),\n",
    "                   tickfont=dict(size=8), range=_xrng),\n",
    "        yaxis=dict(tickfont=dict(size=8)),\n",
    "        template='plotly_white', height=160, width=480,\n",
    "        margin=dict(l=40, r=8, t=28, b=28), showlegend=False)\n",
    "    hb = fig_b.to_html(include_plotlyjs=False, full_html=False,\n",
    "                        config={'displayModeBar': False})\n",
    "\n",
    "    ref_h = ''\n",
    "    if ref:\n",
    "        ref_h = (f'<div style=\"font-size:9px;color:#666;margin-top:2px;\">'\n",
    "                 f'Ref MATLAB: {ref[\"min\"]}–{ref[\"max\"]} mm/d '\n",
    "                 f'(prom {ref[\"mean\"]})</div>')\n",
    "    js = _JS_TMPL2.replace('__DATA__', _json.dumps(raw))\n",
    "\n",
    "    return f\"\"\"<!DOCTYPE html>\n",
    "<html><head><meta charset=\"utf-8\">\n",
    "<script src=\"https://cdn.plot.ly/plotly-2.35.2.min.js\"></script>\n",
    "<style>\n",
    "body{{font-family:'Segoe UI',Arial,sans-serif;margin:0;padding:8px;background:#fefefe;color:#222}}\n",
    ".hdr{{display:flex;align-items:center;gap:8px;border-bottom:3px solid {color};padding-bottom:4px;margin-bottom:5px}}\n",
    ".hdr h3{{margin:0;color:{color};font-size:14px}}\n",
    ".badge{{background:{color};color:#fff;font-size:9px;padding:2px 6px;border-radius:10px}}\n",
    ".info{{font-size:10px;color:#555;line-height:1.4;margin-bottom:4px}}\n",
    ".info b{{color:#333}}\n",
    ".chart-box{{border:1px solid #e8e8e8;border-radius:4px;padding:1px;margin-bottom:4px;background:#fff}}\n",
    ".mc{{font-size:10px;margin-top:2px}}\n",
    ".mc table{{width:100%;border-collapse:collapse}}\n",
    ".mc th{{background:#2c3e50;color:white;padding:2px 5px;font-size:9px;text-align:center}}\n",
    ".mc td{{padding:1px 5px;border-bottom:1px solid #eee;text-align:center;font-size:10px}}\n",
    ".mc td:first-child{{text-align:left}}\n",
    "#rng-info{{text-align:center;font-size:10px;color:#777;margin:2px 0 4px;\n",
    "  background:#f8f9fa;border-radius:4px;padding:3px}}\n",
    "</style></head><body>\n",
    "<div class=\"hdr\"><h3>📍 {tc}</h3><span class=\"badge\">{tp['USCS']}</span></div>\n",
    "<div class=\"info\">\n",
    "  <b>UTM 19S:</b> {utm_c['easting']}E, {utm_c['northing']}N &nbsp;|&nbsp;\n",
    "  <b>Prof:</b> {ds_str}<br>\n",
    "  <b>IDIEM:</b> λ={tp['lambda_sediment']:.3f} W/m·K |\n",
    "  C={tp['C_sediment']/1e6:.3f} MJ/m³·K |\n",
    "  α={tp['alpha_e']:.2e} m²/s\n",
    "</div>\n",
    "<div class=\"chart-box\">{ht}</div>\n",
    "<div class=\"chart-box\">{hf}</div>\n",
    "<div id=\"rng-info\">Ventana: serie completa — mueva el slider o use botones (3d / 1sem / 2sem / Todo)</div>\n",
    "<div class=\"chart-box\">{hb}</div>\n",
    "<div class=\"mc\">\n",
    "  <b>Flujo Hatch-Amp (mm/d) — IQR ventanas deslizantes:</b>\n",
    "  <table><thead><tr>\n",
    "    <th>Par</th><th>Q1</th><th>Mediana</th><th>Q3</th><th>Promedio</th><th>n</th>\n",
    "  </tr></thead>\n",
    "  <tbody id=\"stats-body\"></tbody></table>\n",
    "  {ref_h}\n",
    "</div>\n",
    "{js}\n",
    "</body></html>\"\"\"\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "# Construir Mapa con boxplot horizontal actualizado\n",
    "# ══════════════════════════════════════════════════════════════════════════\n",
    "tc_list2 = list(STATION_COORDS_UTM.keys())\n",
    "clat2 = np.mean([coords_wgs84_v2[t]['lat'] for t in tc_list2])\n",
    "clon2 = np.mean([coords_wgs84_v2[t]['lon'] for t in tc_list2])\n",
    "\n",
    "m2 = folium.Map(location=[clat2, clon2], zoom_start=14,\n",
    "                tiles=None, control_scale=True)\n",
    "folium.TileLayer(\n",
    "    tiles='https://server.arcgisonline.com/ArcGIS/rest/services/'\n",
    "          'World_Imagery/MapServer/tile/{z}/{y}/{x}',\n",
    "    attr='Esri', name='Satélite ESRI', max_zoom=19).add_to(m2)\n",
    "folium.TileLayer(\n",
    "    tiles='https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',\n",
    "    attr='OpenTopoMap', name='Topográfico').add_to(m2)\n",
    "folium.TileLayer(\n",
    "    tiles='https://server.arcgisonline.com/ArcGIS/rest/services/'\n",
    "          'Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',\n",
    "    attr='Esri Labels', name='Etiquetas', overlay=True).add_to(m2)\n",
    "\n",
    "for st2, wgs2 in coords_wgs84_v2.items():\n",
    "    html_pop2 = _build_popup_v2(st2)\n",
    "    iframe2 = folium.IFrame(html=html_pop2, width=520, height=800)\n",
    "    popup2 = folium.Popup(iframe2, max_width=530)\n",
    "    folium.Marker(\n",
    "        location=[wgs2['lat'], wgs2['lon']], popup=popup2,\n",
    "        tooltip=f\"{st2} ({THERMAL_PARAMS_LAB[st2]['USCS']}) — boxplot horizontal\",\n",
    "        icon=folium.Icon(color='red', icon='thermometer-half', prefix='fa')\n",
    "    ).add_to(m2)\n",
    "\n",
    "ordered2 = ['TC5', 'TC4', 'TC3', 'TC2', 'TC1']\n",
    "folium.PolyLine(\n",
    "    [[coords_wgs84_v2[s]['lat'], coords_wgs84_v2[s]['lon']]\n",
    "     for s in ordered2 if s in coords_wgs84_v2],\n",
    "    color='cyan', weight=3, opacity=0.7,\n",
    "    dash_array='10', tooltip='Perfil del río').add_to(m2)\n",
    "\n",
    "folium.plugins.MeasureControl(position='bottomleft').add_to(m2)\n",
    "folium.plugins.Fullscreen().add_to(m2)\n",
    "folium.plugins.MiniMap(toggle_display=True).add_to(m2)\n",
    "folium.LayerControl().add_to(m2)\n",
    "\n",
    "map_path2 = img_dir / 'panel_sig_integrado_horizontal.html'\n",
    "m2.save(str(map_path2))\n",
    "print(f'\\n✅ Mapa SIG con boxplot horizontal: {map_path2.name}')\n",
    "print(f'   → Boxplot horizontal sin outliers en cada popup')\n",
    "print(f'   → {map_path2}')\n",
    "display(m2)"
])


def main():
    # Leer notebook
    with open(NB_PATH, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    cells = nb['cells']

    # Eliminar la celda markdown que se insertó previamente (sec 17 vacía)
    # Buscar y remover celdas markdown que contengan "17. Series Temporales"
    cleaned = []
    for c in cells:
        src = ''.join(c.get('source', []))
        if '17. Series Temporales' in src and c['cell_type'] == 'markdown':
            continue  # skip duplicates
        cleaned.append(c)
    nb['cells'] = cleaned

    # Agregar las 4 nuevas celdas al final
    nb['cells'].extend([md_series, code_series, md_boxplot, code_boxplot])

    # Guardar
    with open(NB_PATH, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

    print(f"✅ {len(nb['cells'])} celdas totales en {NB_PATH.name}")
    print("   → Celda 48: Markdown §17 Series temporales tendencia central")
    print("   → Celda 49: Code — Series temporales (misma escala X-Y)")
    print("   → Celda 50: Markdown §18 Boxplot horizontal")
    print("   → Celda 51: Code — Boxplot horizontal + mapa SIG actualizado")


if __name__ == "__main__":
    main()
